#!/bin/bash
#
# Frontend 执行器
# 负责：分析 PRD、生成前端组件代码、写入文件、运行构建
#
# 用法: execute.sh <run_id> <task_info_path>
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED_DIR="$(dirname "$SCRIPT_DIR")/shared"

# 加载公共基础
source "$SHARED_DIR/execute-base.sh"

# 解析参数
parse_execute_args "$@"

# 打印开始日志
log_execute_start "Frontend"

# ============================================================
# 检查是否跳过执行（稳定性验证）
# ============================================================
if check_skip_execution "component"; then
  output_skip_result
  exit 0
fi

# ============================================================
# [1/5] 分析项目结构
# ============================================================
log_info "[1/5] 分析项目结构..."

# 从任务信息获取目标项目路径
TARGET_PROJECT=$(json_get "$TASK_INFO_PATH" '.project_path' "$PROJECT_DIR/apps/dashboard/frontend")

# 验证 TARGET_PROJECT 路径安全性
if [[ "$TARGET_PROJECT" == *".."* ]]; then
  log_error "路径包含非法字符 '..': $TARGET_PROJECT"
  exit 1
fi

# 使用 realpath 规范化路径并验证在允许目录内
ALLOWED_DIRS=("$PROJECT_DIR" "/home/xx/dev")
TARGET_PROJECT_REAL=$(realpath -m "$TARGET_PROJECT" 2>/dev/null) || {
  log_error "无法解析路径: $TARGET_PROJECT"
  exit 1
}

IN_ALLOWED_DIR=false
for allowed_dir in "${ALLOWED_DIRS[@]}"; do
  if [[ "$TARGET_PROJECT_REAL" == "$allowed_dir"* ]]; then
    IN_ALLOWED_DIR=true
    break
  fi
done

if [[ "$IN_ALLOWED_DIR" != "true" ]]; then
  log_error "目标项目路径不在允许目录内: $TARGET_PROJECT_REAL"
  exit 1
fi

TARGET_PROJECT="$TARGET_PROJECT_REAL"

if [[ ! -d "$TARGET_PROJECT" ]]; then
  log_error "目标项目不存在: $TARGET_PROJECT"
  exit 1
fi

log_info "目标项目: $TARGET_PROJECT"

# 检测前端框架和样式方案 - 一次读取 package.json，避免重复 grep
FRAMEWORK="unknown"
STYLING="css"
if [[ -f "$TARGET_PROJECT/package.json" ]]; then
  PACKAGE_JSON_CONTENT=$(cat "$TARGET_PROJECT/package.json" 2>/dev/null) || PACKAGE_JSON_CONTENT=""

  # P1-10: 检测前端框架（扩展支持 Angular 和 Preact）
  if [[ "$PACKAGE_JSON_CONTENT" == *'"react"'* ]]; then
    FRAMEWORK="react"
  elif [[ "$PACKAGE_JSON_CONTENT" == *'"preact"'* ]]; then
    FRAMEWORK="preact"
  elif [[ "$PACKAGE_JSON_CONTENT" == *'"vue"'* ]]; then
    FRAMEWORK="vue"
  elif [[ "$PACKAGE_JSON_CONTENT" == *'"svelte"'* ]]; then
    FRAMEWORK="svelte"
  elif [[ "$PACKAGE_JSON_CONTENT" == *'"@angular/core"'* ]]; then
    FRAMEWORK="angular"
  fi

  # P1-10: 检测样式方案（扩展支持 SASS 和 LESS）
  if [[ "$PACKAGE_JSON_CONTENT" == *'"tailwindcss"'* ]]; then
    STYLING="tailwind"
  elif [[ "$PACKAGE_JSON_CONTENT" == *'"styled-components"'* ]]; then
    STYLING="styled-components"
  elif [[ "$PACKAGE_JSON_CONTENT" == *'"@emotion"'* ]]; then
    STYLING="emotion"
  elif [[ "$PACKAGE_JSON_CONTENT" == *'"sass"'* ]] || [[ "$PACKAGE_JSON_CONTENT" == *'"node-sass"'* ]]; then
    STYLING="sass"
  elif [[ "$PACKAGE_JSON_CONTENT" == *'"less"'* ]]; then
    STYLING="less"
  fi
fi

log_info "框架: $FRAMEWORK, 样式: $STYLING"

# ============================================================
# [2/5] 调用 Claude 生成组件
# ============================================================
log_info "[2/5] 调用 Claude 生成组件..."

# 提前检查磁盘空间，避免文件创建后才发现空间不足
check_disk_space "$WORK_DIR" 100 || exit 1

FILES_CHANGED=()
FILES_FAILED=()
COMPONENT_COUNT=0

if [[ "${TEST_MODE:-}" == "1" ]]; then
  log_info "[TEST_MODE] 使用 mock 组件生成"

  # 创建 mock 组件文件
  MOCK_COMPONENT="$TARGET_PROJECT/src/components/MockFeature-${RUN_ID}.tsx"

  # P0-1: 二次验证 Mock 组件路径安全性
  MOCK_COMPONENT_REAL=$(realpath -m "$MOCK_COMPONENT" 2>/dev/null) || {
    log_error "无法解析 Mock 组件路径: $MOCK_COMPONENT"
    exit 1
  }

  # 验证路径在 TARGET_PROJECT 目录内（使用显式前缀检查）
  if [[ "$MOCK_COMPONENT_REAL" != "$TARGET_PROJECT/"* ]]; then
    log_error "Mock 组件路径超出目标项目范围: $MOCK_COMPONENT_REAL"
    exit 1
  fi

  MOCK_COMPONENT="$MOCK_COMPONENT_REAL"

  mkdir -p "$(dirname "$MOCK_COMPONENT")" || {
    log_error "无法创建目录: $(dirname "$MOCK_COMPONENT")"
    exit 1
  }

  cat > "$MOCK_COMPONENT" <<'EOF'
/**
 * Mock Feature Component
 * Generated by AI Factory Frontend Executor
 */

import React from 'react';

interface MockFeatureProps {
  title: string;
  description?: string;
  onAction?: () => void;
}

export const MockFeature: React.FC<MockFeatureProps> = ({
  title,
  description,
  onAction,
}) => {
  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <h3 className="text-lg font-semibold text-gray-900">{title}</h3>
      {description && (
        <p className="mt-2 text-sm text-gray-600">{description}</p>
      )}
      {onAction && (
        <button
          onClick={onAction}
          className="mt-4 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
        >
          Action
        </button>
      )}
    </div>
  );
};

export default MockFeature;
EOF

  FILES_CHANGED+=("$MOCK_COMPONENT")
  COMPONENT_COUNT=1
  log_info "Mock 组件已创建: $MOCK_COMPONENT"
else
  PROMPT="根据以下任务描述，生成前端组件代码。

任务名: $TASK_NAME
任务描述:
$TASK_CONTENT

项目路径: $TARGET_PROJECT
框架: $FRAMEWORK
样式方案: $STYLING

要求：
1. 分析任务需求，确定需要创建的组件
2. 生成符合项目风格的组件代码
3. 使用 TypeScript 类型定义
4. 组件应该是响应式的
5. 使用 ${STYLING} 进行样式处理
6. 包含必要的 props 类型定义

请输出 JSON 格式：
{
  \"components\": [
    {
      \"path\": \"相对路径\",
      \"name\": \"组件名\",
      \"content\": \"文件内容\"
    }
  ],
  \"summary\": \"变更摘要\"
}"

  if ! call_claude "$PROMPT" 600; then
    # P1-7: 记录详细的失败上下文
    log_error "Claude 调用失败，记录上下文信息"
    {
      echo "=== Claude 调用失败上下文 ==="
      echo "时间: $(date -Iseconds)"
      echo "任务名: $TASK_NAME"
      echo "任务 ID: $TASK_ID"
      echo "目标项目: $TARGET_PROJECT"
      echo "框架: $FRAMEWORK"
      echo "样式: $STYLING"
      echo "=== END ==="
    } >> "$WORK_DIR/claude_error_context.txt"
    chmod 600 "$WORK_DIR/claude_error_context.txt" 2>/dev/null || true
    exit 1
  fi

  CODE_OUTPUT=$(extract_json_from_claude "$CLAUDE_OUTPUT") || {
    log_error "无法解析 Claude 输出"
    exit 1
  }

  # P0-2: 验证 CODE_OUTPUT 是有效的 JSON 对象
  if ! echo "$CODE_OUTPUT" | jq -e 'type == "object"' >/dev/null 2>&1; then
    log_error "CODE_OUTPUT 不是有效的 JSON 对象"
    exit 1
  fi

  # P0-2: 验证 .components 存在且是数组
  if ! echo "$CODE_OUTPUT" | jq -e '.components | type == "array"' >/dev/null 2>&1; then
    log_error "CODE_OUTPUT.components 不存在或不是数组"
    exit 1
  fi

  # 解析并写入文件
  COMPONENT_COUNT=$(echo "$CODE_OUTPUT" | jq '.components | length')

  # 验证 COMPONENT_COUNT 是有效数字且在合理范围内
  if ! [[ "$COMPONENT_COUNT" =~ ^[0-9]+$ ]]; then
    log_error "COMPONENT_COUNT 不是有效数字: $COMPONENT_COUNT"
    exit 1
  fi

  if [[ "$COMPONENT_COUNT" -lt 0 ]] || [[ "$COMPONENT_COUNT" -gt 100 ]]; then
    log_error "COMPONENT_COUNT 超出合理范围 (0-100): $COMPONENT_COUNT"
    exit 1
  fi

  for ((i=0; i<COMPONENT_COUNT; i++)); do
    COMP_PATH=$(echo "$CODE_OUTPUT" | jq -r ".components[$i].path // empty")
    COMP_NAME=$(echo "$CODE_OUTPUT" | jq -r ".components[$i].name // empty")
    COMP_CONTENT=$(echo "$CODE_OUTPUT" | jq -r ".components[$i].content // empty")

    # P1-9: 验证必要字段非空，同时检查 "null" 字符串（jq 可能返回字面量 "null"）
    if [[ -z "$COMP_PATH" ]] || [[ "$COMP_PATH" == "null" ]]; then
      log_error "组件路径为空或 null (索引 $i)，跳过"
      continue
    fi
    if [[ -z "$COMP_NAME" ]] || [[ "$COMP_NAME" == "null" ]]; then
      log_warn "组件名为空或 null (索引 $i): $COMP_PATH，使用路径作为名称"
      COMP_NAME=$(basename "$COMP_PATH")
    fi
    if [[ -z "$COMP_CONTENT" ]] || [[ "$COMP_CONTENT" == "null" ]]; then
      log_warn "组件内容为空或 null (索引 $i): $COMP_PATH，跳过"
      continue
    fi

    # 验证 COMP_PATH 不包含路径遍历字符
    if [[ "$COMP_PATH" == *".."* ]] || [[ "$COMP_PATH" == /* ]]; then
      log_error "组件路径包含非法字符: $COMP_PATH"
      continue
    fi

    FULL_PATH="$TARGET_PROJECT/$COMP_PATH"

    # 使用 realpath 验证最终路径在目标项目内
    FULL_PATH_REAL=$(realpath -m "$FULL_PATH" 2>/dev/null) || {
      log_error "无法解析组件路径: $FULL_PATH"
      continue
    }

    # P0-5: 路径安全验证：使用显式前缀检查，必须以 TARGET_PROJECT/ 开头
    # 注意：必须检查 "$TARGET_PROJECT/" 而不是 "$TARGET_PROJECT"，防止 /target-project-evil 绕过
    if [[ "$FULL_PATH_REAL" == "$TARGET_PROJECT" ]]; then
      log_error "安全错误: 不能写入项目根目录本身"
      continue
    elif [[ "$FULL_PATH_REAL" != "$TARGET_PROJECT/"* ]]; then
      log_error "组件路径超出目标项目范围: $FULL_PATH_REAL (期望前缀: $TARGET_PROJECT/)"
      continue
    fi

    mkdir -p "$(dirname "$FULL_PATH_REAL")" || {
      log_error "无法创建目录: $(dirname "$FULL_PATH_REAL")"
      continue
    }

    # 使用 printf 避免 echo 的 -e/-n 问题
    if ! printf '%s\n' "$COMP_CONTENT" > "$FULL_PATH_REAL"; then
      log_error "无法写入文件: $FULL_PATH_REAL"
      # P1-8: 记录失败文件用于后续回滚
      FILES_FAILED+=("$FULL_PATH_REAL")
      continue
    fi

    # P0-3: 设置正确的文件权限
    chmod 644 "$FULL_PATH_REAL" || {
      log_warn "无法设置文件权限: $FULL_PATH_REAL"
    }

    FILES_CHANGED+=("$FULL_PATH_REAL")
    log_info "[创建] $COMP_NAME -> $COMP_PATH"
  done

  # P1-8: 如果有失败的文件且需要回滚，清理已创建的文件
  if [[ ${#FILES_FAILED[@]} -gt 0 ]]; then
    log_warn "有 ${#FILES_FAILED[@]} 个文件写入失败"
    # 记录失败文件列表
    printf '%s\n' "${FILES_FAILED[@]}" > "$WORK_DIR/files_failed.txt"
  fi
fi

# 保存变更文件列表
if [[ ${#FILES_CHANGED[@]} -gt 0 ]]; then
  printf '%s\n' "${FILES_CHANGED[@]}" > "$WORK_DIR/files_changed.txt"
else
  : > "$WORK_DIR/files_changed.txt"
fi
log_info "共创建 ${#FILES_CHANGED[@]} 个组件文件"

# ============================================================
# [3/5] TypeScript 类型检查
# ============================================================
log_info "[3/5] TypeScript 类型检查..."

TSC_RESULT="skipped"
TSC_OUTPUT=""

if [[ "${TEST_MODE:-}" == "1" ]]; then
  local tsc_timeout="${TSC_TIMEOUT:-120}"
  if [[ "$tsc_timeout" -lt 5 ]]; then
    log_warn "[TEST_MODE] 模拟 TSC 超时 (TSC_TIMEOUT=$tsc_timeout < 5)"
    TSC_RESULT="timeout"
    TSC_OUTPUT="[TEST_MODE] Simulated TSC timeout"
  else
    log_info "[TEST_MODE] 模拟类型检查通过"
    TSC_RESULT="passed"
  fi
else
  if [[ -f "$TARGET_PROJECT/tsconfig.json" ]]; then
    if command -v npx &>/dev/null; then
      log_info "运行 tsc --noEmit (timeout 120s)..."
      # P0-4: 使用子 shell 隔离 cd 命令，避免影响主进程工作目录
      TSC_OUTPUT=$(
        cd "$TARGET_PROJECT" 2>/dev/null || {
          echo "Failed to cd to project directory"
          exit 1
        }
        timeout 120 npx tsc --noEmit 2>&1
      )
      TSC_EXIT_CODE=$?
      if [[ $TSC_EXIT_CODE -eq 0 ]]; then
        TSC_RESULT="passed"
      elif [[ $TSC_EXIT_CODE -eq 124 ]]; then
        TSC_RESULT="timeout"
        log_warn "TypeScript 类型检查超时 (120s)"
      elif [[ $TSC_EXIT_CODE -eq 1 ]] && [[ "$TSC_OUTPUT" == "Failed to cd to project directory" ]]; then
        log_error "无法切换到项目目录: $TARGET_PROJECT"
        TSC_RESULT="failed"
      else
        TSC_RESULT="warning"
      fi
    fi
  else
    log_info "未找到 tsconfig.json，跳过类型检查"
  fi
fi

log_info "类型检查结果: $TSC_RESULT"

# ============================================================
# [4/5] 运行构建
# ============================================================
log_info "[4/5] 运行构建..."

BUILD_RESULT="skipped"
BUILD_OUTPUT=""

if [[ "${TEST_MODE:-}" == "1" ]]; then
  local build_timeout="${BUILD_TIMEOUT:-300}"
  if [[ "$build_timeout" -lt 5 ]]; then
    log_warn "[TEST_MODE] 模拟 Build 超时 (BUILD_TIMEOUT=$build_timeout < 5)"
    BUILD_RESULT="timeout"
    BUILD_OUTPUT="[TEST_MODE] Simulated Build timeout"
  else
    log_info "[TEST_MODE] 模拟构建通过"
    BUILD_RESULT="passed"
  fi
else
  # 使用已读取的 PACKAGE_JSON_CONTENT 检查 build 脚本
  if [[ -f "$TARGET_PROJECT/package.json" ]] && [[ "$PACKAGE_JSON_CONTENT" == *'"build"'* ]]; then
    log_info "运行 npm run build (timeout 300s)..."
    # P0-4: 使用子 shell 隔离 cd 命令，避免影响主进程工作目录
    BUILD_OUTPUT=$(
      cd "$TARGET_PROJECT" 2>/dev/null || {
        echo "Failed to cd to project directory"
        exit 1
      }
      timeout 300 npm run build 2>&1
    )
    BUILD_EXIT_CODE=$?
    if [[ $BUILD_EXIT_CODE -eq 0 ]]; then
      BUILD_RESULT="passed"
    elif [[ $BUILD_EXIT_CODE -eq 124 ]]; then
      BUILD_RESULT="timeout"
      log_warn "构建超时 (300s)"
    elif [[ $BUILD_EXIT_CODE -eq 1 ]] && [[ "$BUILD_OUTPUT" == "Failed to cd to project directory" ]]; then
      log_error "无法切换到项目目录: $TARGET_PROJECT"
      BUILD_RESULT="failed"
    else
      BUILD_RESULT="failed"
    fi
  else
    log_info "未配置构建脚本，跳过"
  fi
fi

log_info "构建结果: $BUILD_RESULT"

# ============================================================
# 保存结果
# ============================================================
RESULT_SUCCESS=true
if [[ "$TSC_RESULT" == "failed" ]] || [[ "$TSC_RESULT" == "timeout" ]]; then
  RESULT_SUCCESS=false
fi
if [[ "$BUILD_RESULT" == "failed" ]] || [[ "$BUILD_RESULT" == "timeout" ]]; then
  RESULT_SUCCESS=false
fi

RESULT_ARTIFACTS=$(jq -n \
  --arg type "component" \
  --arg id "frontend-${RUN_ID}" \
  --arg project "$TARGET_PROJECT" \
  --arg framework "$FRAMEWORK" \
  --arg styling "$STYLING" \
  --argjson component_count "$COMPONENT_COUNT" \
  --arg tsc_result "$TSC_RESULT" \
  --arg build_result "$BUILD_RESULT" \
  '[{
    type: $type,
    id: $id,
    name: "Frontend Component Generation",
    project: $project,
    framework: $framework,
    styling: $styling,
    components_created: $component_count,
    tsc_result: $tsc_result,
    build_result: $build_result
  }]')

save_result

# ============================================================
# [5/5] 生成截图报告
# ============================================================
log_info "[5/5] 生成执行结果截图..."

# P0-6: 对所有用户可控输入进行 HTML 转义
SAFE_PROJECT=$(html_escape "$TARGET_PROJECT")
SAFE_FRAMEWORK=$(html_escape "$FRAMEWORK")
SAFE_STYLING=$(html_escape "$STYLING")
SAFE_TSC_RESULT=$(html_escape "$TSC_RESULT")
SAFE_BUILD_RESULT=$(html_escape "$BUILD_RESULT")

# 生成组件列表 HTML
COMPONENTS_HTML=""
for f in "${FILES_CHANGED[@]}"; do
  SAFE_F=$(html_escape "$(basename "$f")")
  COMPONENTS_HTML+="<div class=\"info-row\"><span class=\"info-value\">🧩 ${SAFE_F}</span></div>"
done

MAIN_CONTENT="
<div class=\"grid\">
  <div class=\"card\">
    <div class=\"card-title\">组件数量</div>
    <div class=\"card-value\">${#FILES_CHANGED[@]} 个</div>
  </div>
  <div class=\"card\">
    <div class=\"card-title\">框架</div>
    <div class=\"card-value\">${SAFE_FRAMEWORK}</div>
  </div>
</div>
<div class=\"card\">
  <div class=\"card-title\">目标项目</div>
  <div class=\"card-value\" style=\"font-size: 16px;\">${SAFE_PROJECT}</div>
</div>
<div class=\"card\">
  <div class=\"info-row\">
    <span class=\"info-label\">样式方案</span>
    <span class=\"info-value\">${SAFE_STYLING}</span>
  </div>
</div>
<div class=\"card\">
  <div class=\"card-title\">类型检查</div>
  <div class=\"card-value $([ "$TSC_RESULT" == "passed" ] && echo "success")\">
    $([ "$TSC_RESULT" == "passed" ] && echo "✅" || echo "⚠️") ${SAFE_TSC_RESULT}
  </div>
</div>
<div class=\"card\">
  <div class=\"card-title\">构建结果</div>
  <div class=\"card-value $([ "$BUILD_RESULT" == "passed" ] && echo "success")\">
    $([ "$BUILD_RESULT" == "passed" ] && echo "✅" || echo "⚠️") ${SAFE_BUILD_RESULT}
  </div>
</div>
<div class=\"card\">
  <div class=\"card-title\">创建的组件</div>
  ${COMPONENTS_HTML}
</div>
"

REPORT_HTML=$(generate_result_report_html "Frontend 组件生成完成" "✅" "$MAIN_CONTENT")
screenshot_html_report "$RUN_ID" "frontend-execute-result" "$REPORT_HTML" || log_warn "结果截图失败"

# ============================================================
# 完成
# ============================================================
log_execute_end "Frontend"

jq -n \
  --argjson success "$RESULT_SUCCESS" \
  --arg project "$TARGET_PROJECT" \
  --arg framework "$FRAMEWORK" \
  --arg styling "$STYLING" \
  --argjson component_count "$COMPONENT_COUNT" \
  --arg tsc_result "$TSC_RESULT" \
  --arg build_result "$BUILD_RESULT" \
  '{
    success: $success,
    project: $project,
    framework: $framework,
    styling: $styling,
    components_created: $component_count,
    tsc_result: $tsc_result,
    build_result: $build_result
  }'
