#!/bin/bash
#
# Frontend 执行器
# 负责：分析 PRD、生成前端组件代码、写入文件、运行构建
#
# 用法: execute.sh <run_id> <task_info_path>
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED_DIR="$(dirname "$SCRIPT_DIR")/shared"

# 加载公共基础
source "$SHARED_DIR/execute-base.sh"

# 解析参数
parse_execute_args "$@"

# 打印开始日志
log_execute_start "Frontend"

# ============================================================
# 检查是否跳过执行（稳定性验证）
# ============================================================
if check_skip_execution "component"; then
  output_skip_result
  exit 0
fi

# ============================================================
# [1/5] 分析项目结构
# ============================================================
log_info "[1/5] 分析项目结构..."

# 从任务信息获取目标项目路径
TARGET_PROJECT=$(json_get "$TASK_INFO_PATH" '.project_path' "$PROJECT_DIR/apps/dashboard/frontend")

# 验证 TARGET_PROJECT 路径安全性
if [[ "$TARGET_PROJECT" == *".."* ]]; then
  log_error "路径包含非法字符 '..': $TARGET_PROJECT"
  exit 1
fi

# 使用 realpath 规范化路径并验证在允许目录内
ALLOWED_DIRS=("$PROJECT_DIR" "/home/xx/dev")
TARGET_PROJECT_REAL=$(realpath -m "$TARGET_PROJECT" 2>/dev/null) || {
  log_error "无法解析路径: $TARGET_PROJECT"
  exit 1
}

IN_ALLOWED_DIR=false
for allowed_dir in "${ALLOWED_DIRS[@]}"; do
  if [[ "$TARGET_PROJECT_REAL" == "$allowed_dir"* ]]; then
    IN_ALLOWED_DIR=true
    break
  fi
done

if [[ "$IN_ALLOWED_DIR" != "true" ]]; then
  log_error "目标项目路径不在允许目录内: $TARGET_PROJECT_REAL"
  exit 1
fi

TARGET_PROJECT="$TARGET_PROJECT_REAL"

if [[ ! -d "$TARGET_PROJECT" ]]; then
  log_error "目标项目不存在: $TARGET_PROJECT"
  exit 1
fi

log_info "目标项目: $TARGET_PROJECT"

# 检测前端框架
FRAMEWORK="unknown"
if [[ -f "$TARGET_PROJECT/package.json" ]]; then
  if grep -q '"react"' "$TARGET_PROJECT/package.json" 2>/dev/null; then
    FRAMEWORK="react"
  elif grep -q '"vue"' "$TARGET_PROJECT/package.json" 2>/dev/null; then
    FRAMEWORK="vue"
  elif grep -q '"svelte"' "$TARGET_PROJECT/package.json" 2>/dev/null; then
    FRAMEWORK="svelte"
  fi
fi

# 检测样式方案
STYLING="css"
if grep -q '"tailwindcss"' "$TARGET_PROJECT/package.json" 2>/dev/null; then
  STYLING="tailwind"
elif grep -q '"styled-components"' "$TARGET_PROJECT/package.json" 2>/dev/null; then
  STYLING="styled-components"
elif grep -q '"@emotion"' "$TARGET_PROJECT/package.json" 2>/dev/null; then
  STYLING="emotion"
fi

log_info "框架: $FRAMEWORK, 样式: $STYLING"

# ============================================================
# [2/5] 调用 Claude 生成组件
# ============================================================
log_info "[2/5] 调用 Claude 生成组件..."

FILES_CHANGED=()
COMPONENT_COUNT=0

if [[ "${TEST_MODE:-}" == "1" ]]; then
  log_info "[TEST_MODE] 使用 mock 组件生成"

  # 创建 mock 组件文件
  MOCK_COMPONENT="$TARGET_PROJECT/src/components/MockFeature-${RUN_ID}.tsx"
  mkdir -p "$(dirname "$MOCK_COMPONENT")"

  cat > "$MOCK_COMPONENT" <<'EOF'
/**
 * Mock Feature Component
 * Generated by AI Factory Frontend Executor
 */

import React from 'react';

interface MockFeatureProps {
  title: string;
  description?: string;
  onAction?: () => void;
}

export const MockFeature: React.FC<MockFeatureProps> = ({
  title,
  description,
  onAction,
}) => {
  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <h3 className="text-lg font-semibold text-gray-900">{title}</h3>
      {description && (
        <p className="mt-2 text-sm text-gray-600">{description}</p>
      )}
      {onAction && (
        <button
          onClick={onAction}
          className="mt-4 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
        >
          Action
        </button>
      )}
    </div>
  );
};

export default MockFeature;
EOF

  FILES_CHANGED+=("$MOCK_COMPONENT")
  COMPONENT_COUNT=1
  log_info "Mock 组件已创建: $MOCK_COMPONENT"
else
  PROMPT="根据以下任务描述，生成前端组件代码。

任务名: $TASK_NAME
任务描述:
$TASK_CONTENT

项目路径: $TARGET_PROJECT
框架: $FRAMEWORK
样式方案: $STYLING

要求：
1. 分析任务需求，确定需要创建的组件
2. 生成符合项目风格的组件代码
3. 使用 TypeScript 类型定义
4. 组件应该是响应式的
5. 使用 ${STYLING} 进行样式处理
6. 包含必要的 props 类型定义

请输出 JSON 格式：
{
  \"components\": [
    {
      \"path\": \"相对路径\",
      \"name\": \"组件名\",
      \"content\": \"文件内容\"
    }
  ],
  \"summary\": \"变更摘要\"
}"

  if ! call_claude "$PROMPT" 600; then
    exit 1
  fi

  CODE_OUTPUT=$(extract_json_from_claude "$CLAUDE_OUTPUT") || {
    log_error "无法解析 Claude 输出"
    exit 1
  }

  # 解析并写入文件
  COMPONENT_COUNT=$(echo "$CODE_OUTPUT" | jq '.components | length')

  # 验证 COMPONENT_COUNT 是有效数字且在合理范围内
  if ! [[ "$COMPONENT_COUNT" =~ ^[0-9]+$ ]]; then
    log_error "COMPONENT_COUNT 不是有效数字: $COMPONENT_COUNT"
    exit 1
  fi

  if [[ "$COMPONENT_COUNT" -lt 0 ]] || [[ "$COMPONENT_COUNT" -gt 100 ]]; then
    log_error "COMPONENT_COUNT 超出合理范围 (0-100): $COMPONENT_COUNT"
    exit 1
  fi

  for ((i=0; i<COMPONENT_COUNT; i++)); do
    COMP_PATH=$(echo "$CODE_OUTPUT" | jq -r ".components[$i].path")
    COMP_NAME=$(echo "$CODE_OUTPUT" | jq -r ".components[$i].name")
    COMP_CONTENT=$(echo "$CODE_OUTPUT" | jq -r ".components[$i].content")

    # 验证 COMP_PATH 不包含路径遍历字符
    if [[ "$COMP_PATH" == *".."* ]] || [[ "$COMP_PATH" == /* ]]; then
      log_error "组件路径包含非法字符: $COMP_PATH"
      continue
    fi

    FULL_PATH="$TARGET_PROJECT/$COMP_PATH"

    # 使用 realpath 验证最终路径在目标项目内
    FULL_PATH_REAL=$(realpath -m "$FULL_PATH" 2>/dev/null) || {
      log_error "无法解析组件路径: $FULL_PATH"
      continue
    }

    if [[ "$FULL_PATH_REAL" != "$TARGET_PROJECT"* ]]; then
      log_error "组件路径超出目标项目范围: $FULL_PATH_REAL"
      continue
    fi

    mkdir -p "$(dirname "$FULL_PATH_REAL")"

    echo "$COMP_CONTENT" > "$FULL_PATH_REAL"
    FILES_CHANGED+=("$FULL_PATH_REAL")
    log_info "[创建] $COMP_NAME -> $COMP_PATH"
  done
fi

# 检查磁盘空间
check_disk_space "$WORK_DIR" 100 || exit 1

# 保存变更文件列表
if [[ ${#FILES_CHANGED[@]} -gt 0 ]]; then
  printf '%s\n' "${FILES_CHANGED[@]}" > "$WORK_DIR/files_changed.txt"
else
  : > "$WORK_DIR/files_changed.txt"
fi
log_info "共创建 ${#FILES_CHANGED[@]} 个组件文件"

# ============================================================
# [3/5] TypeScript 类型检查
# ============================================================
log_info "[3/5] TypeScript 类型检查..."

TSC_RESULT="skipped"
TSC_OUTPUT=""

if [[ "${TEST_MODE:-}" == "1" ]]; then
  log_info "[TEST_MODE] 模拟类型检查通过"
  TSC_RESULT="passed"
else
  if [[ -f "$TARGET_PROJECT/tsconfig.json" ]]; then
    if command -v npx &>/dev/null; then
      log_info "运行 tsc --noEmit (timeout 120s)..."
      TSC_OUTPUT=$(
        cd "$TARGET_PROJECT" && timeout 120 npx tsc --noEmit 2>&1
      )
      TSC_EXIT_CODE=$?
      if [[ $TSC_EXIT_CODE -eq 0 ]]; then
        TSC_RESULT="passed"
      elif [[ $TSC_EXIT_CODE -eq 124 ]]; then
        TSC_RESULT="timeout"
        log_warn "TypeScript 类型检查超时 (120s)"
      else
        TSC_RESULT="warning"
      fi
    fi
  else
    log_info "未找到 tsconfig.json，跳过类型检查"
  fi
fi

log_info "类型检查结果: $TSC_RESULT"

# ============================================================
# [4/5] 运行构建
# ============================================================
log_info "[4/5] 运行构建..."

BUILD_RESULT="skipped"
BUILD_OUTPUT=""

if [[ "${TEST_MODE:-}" == "1" ]]; then
  log_info "[TEST_MODE] 模拟构建通过"
  BUILD_RESULT="passed"
else
  if [[ -f "$TARGET_PROJECT/package.json" ]] && grep -q '"build"' "$TARGET_PROJECT/package.json"; then
    log_info "运行 npm run build (timeout 300s)..."
    BUILD_OUTPUT=$(
      cd "$TARGET_PROJECT" && timeout 300 npm run build 2>&1
    )
    BUILD_EXIT_CODE=$?
    if [[ $BUILD_EXIT_CODE -eq 0 ]]; then
      BUILD_RESULT="passed"
    elif [[ $BUILD_EXIT_CODE -eq 124 ]]; then
      BUILD_RESULT="timeout"
      log_warn "构建超时 (300s)"
    else
      BUILD_RESULT="failed"
    fi
  else
    log_info "未配置构建脚本，跳过"
  fi
fi

log_info "构建结果: $BUILD_RESULT"

# ============================================================
# 保存结果
# ============================================================
RESULT_SUCCESS=true
if [[ "$TSC_RESULT" == "failed" ]] || [[ "$TSC_RESULT" == "timeout" ]]; then
  RESULT_SUCCESS=false
fi
if [[ "$BUILD_RESULT" == "failed" ]] || [[ "$BUILD_RESULT" == "timeout" ]]; then
  RESULT_SUCCESS=false
fi

RESULT_ARTIFACTS=$(jq -n \
  --arg type "component" \
  --arg id "frontend-${RUN_ID}" \
  --arg project "$TARGET_PROJECT" \
  --arg framework "$FRAMEWORK" \
  --arg styling "$STYLING" \
  --argjson component_count "$COMPONENT_COUNT" \
  --arg tsc_result "$TSC_RESULT" \
  --arg build_result "$BUILD_RESULT" \
  '[{
    type: $type,
    id: $id,
    name: "Frontend Component Generation",
    project: $project,
    framework: $framework,
    styling: $styling,
    components_created: $component_count,
    tsc_result: $tsc_result,
    build_result: $build_result
  }]')

save_result

# ============================================================
# [5/5] 生成截图报告
# ============================================================
log_info "[5/5] 生成执行结果截图..."

SAFE_PROJECT=$(html_escape "$TARGET_PROJECT")

# 生成组件列表 HTML
COMPONENTS_HTML=""
for f in "${FILES_CHANGED[@]}"; do
  SAFE_F=$(html_escape "$(basename "$f")")
  COMPONENTS_HTML+="<div class=\"info-row\"><span class=\"info-value\">🧩 ${SAFE_F}</span></div>"
done

MAIN_CONTENT="
<div class=\"grid\">
  <div class=\"card\">
    <div class=\"card-title\">组件数量</div>
    <div class=\"card-value\">${#FILES_CHANGED[@]} 个</div>
  </div>
  <div class=\"card\">
    <div class=\"card-title\">框架</div>
    <div class=\"card-value\">${FRAMEWORK}</div>
  </div>
</div>
<div class=\"card\">
  <div class=\"card-title\">目标项目</div>
  <div class=\"card-value\" style=\"font-size: 16px;\">${SAFE_PROJECT}</div>
</div>
<div class=\"card\">
  <div class=\"info-row\">
    <span class=\"info-label\">样式方案</span>
    <span class=\"info-value\">${STYLING}</span>
  </div>
</div>
<div class=\"card\">
  <div class=\"card-title\">类型检查</div>
  <div class=\"card-value $([ "$TSC_RESULT" == "passed" ] && echo "success")\">
    $([ "$TSC_RESULT" == "passed" ] && echo "✅" || echo "⚠️") ${TSC_RESULT}
  </div>
</div>
<div class=\"card\">
  <div class=\"card-title\">构建结果</div>
  <div class=\"card-value $([ "$BUILD_RESULT" == "passed" ] && echo "success")\">
    $([ "$BUILD_RESULT" == "passed" ] && echo "✅" || echo "⚠️") ${BUILD_RESULT}
  </div>
</div>
<div class=\"card\">
  <div class=\"card-title\">创建的组件</div>
  ${COMPONENTS_HTML}
</div>
"

REPORT_HTML=$(generate_result_report_html "Frontend 组件生成完成" "✅" "$MAIN_CONTENT")
screenshot_html_report "$RUN_ID" "frontend-execute-result" "$REPORT_HTML" || log_warn "结果截图失败"

# ============================================================
# 完成
# ============================================================
log_execute_end "Frontend"

jq -n \
  --argjson success "$RESULT_SUCCESS" \
  --arg project "$TARGET_PROJECT" \
  --arg framework "$FRAMEWORK" \
  --arg styling "$STYLING" \
  --argjson component_count "$COMPONENT_COUNT" \
  --arg tsc_result "$TSC_RESULT" \
  --arg build_result "$BUILD_RESULT" \
  '{
    success: $success,
    project: $project,
    framework: $framework,
    styling: $styling,
    components_created: $component_count,
    tsc_result: $tsc_result,
    build_result: $build_result
  }'
