#!/bin/bash
#
# Backend 执行器
# 负责：分析 PRD、生成后端代码、写入文件、运行测试
#
# 用法: execute.sh <run_id> <task_info_path>
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED_DIR="$(dirname "$SCRIPT_DIR")/shared"

# 加载公共基础
source "$SHARED_DIR/execute-base.sh"

# 解析参数
parse_execute_args "$@"

# 打印开始日志
log_execute_start "Backend"

# ============================================================
# 检查是否跳过执行（稳定性验证）
# ============================================================
if check_skip_execution "code"; then
  output_skip_result
  exit 0
fi

# ============================================================
# [1/5] 分析项目结构
# ============================================================
log_info "[1/5] 分析项目结构..."

# 从任务信息获取目标项目路径
TARGET_PROJECT=$(json_get "$TASK_INFO_PATH" '.project_path' "$PROJECT_DIR/apps/dashboard")

if [[ ! -d "$TARGET_PROJECT" ]]; then
  log_error "目标项目不存在: $TARGET_PROJECT"
  exit 1
fi

log_info "目标项目: $TARGET_PROJECT"

# 检测项目类型
PROJECT_TYPE="unknown"
if [[ -f "$TARGET_PROJECT/package.json" ]]; then
  if grep -q '"typescript"' "$TARGET_PROJECT/package.json" 2>/dev/null; then
    PROJECT_TYPE="typescript"
  else
    PROJECT_TYPE="javascript"
  fi
elif [[ -f "$TARGET_PROJECT/requirements.txt" ]] || [[ -f "$TARGET_PROJECT/pyproject.toml" ]]; then
  PROJECT_TYPE="python"
fi

log_info "项目类型: $PROJECT_TYPE"

# ============================================================
# [2/5] 调用 Claude 生成代码
# ============================================================
log_info "[2/5] 调用 Claude 生成代码..."

FILES_CHANGED=()
CODE_OUTPUT=""

if [[ "${TEST_MODE:-}" == "1" ]]; then
  log_info "[TEST_MODE] 使用 mock 代码生成"

  # 创建 mock 文件 (使用 core 目录或 src 目录)
  if [[ -d "$TARGET_PROJECT/core" ]]; then
    MOCK_FILE="$TARGET_PROJECT/core/mock-feature-${RUN_ID}.ts"
  else
    MOCK_FILE="$TARGET_PROJECT/src/mock-feature-${RUN_ID}.ts"
  fi
  mkdir -p "$(dirname "$MOCK_FILE")"

  cat > "$MOCK_FILE" <<'EOF'
/**
 * Mock feature generated by AI Factory
 * This is a test file for backend executor
 */

export interface MockFeature {
  id: string;
  name: string;
  createdAt: Date;
}

export function createMockFeature(name: string): MockFeature {
  return {
    id: `mock-${Date.now()}`,
    name,
    createdAt: new Date(),
  };
}

export function getMockFeatures(): MockFeature[] {
  return [
    createMockFeature('Feature 1'),
    createMockFeature('Feature 2'),
  ];
}
EOF

  FILES_CHANGED+=("$MOCK_FILE")
  CODE_OUTPUT="Created mock feature file"
  log_info "Mock 文件已创建: $MOCK_FILE"
else
  PROMPT="根据以下任务描述，生成后端代码。

任务名: $TASK_NAME
任务描述:
$TASK_CONTENT

项目路径: $TARGET_PROJECT
项目类型: $PROJECT_TYPE

要求：
1. 分析任务需求，确定需要创建或修改的文件
2. 生成符合项目风格的代码
3. 包含必要的类型定义（TypeScript）或类型注解（Python）
4. 添加适当的错误处理
5. 如果需要新增 API 端点，遵循 RESTful 规范

请输出 JSON 格式：
{
  \"files\": [
    {
      \"path\": \"相对路径\",
      \"action\": \"create|modify\",
      \"content\": \"文件内容\"
    }
  ],
  \"summary\": \"变更摘要\"
}"

  if ! call_claude "$PROMPT" 600; then
    exit 1
  fi

  CODE_OUTPUT=$(extract_json_from_claude "$CLAUDE_OUTPUT") || {
    log_error "无法解析 Claude 输出"
    exit 1
  }

  # 解析并写入文件
  FILE_COUNT=$(echo "$CODE_OUTPUT" | jq '.files | length')

  for ((i=0; i<FILE_COUNT; i++)); do
    FILE_PATH=$(echo "$CODE_OUTPUT" | jq -r ".files[$i].path")
    FILE_ACTION=$(echo "$CODE_OUTPUT" | jq -r ".files[$i].action")
    FILE_CONTENT=$(echo "$CODE_OUTPUT" | jq -r ".files[$i].content")

    FULL_PATH="$TARGET_PROJECT/$FILE_PATH"
    mkdir -p "$(dirname "$FULL_PATH")"

    echo "$FILE_CONTENT" > "$FULL_PATH"
    FILES_CHANGED+=("$FULL_PATH")
    log_info "[$FILE_ACTION] $FILE_PATH"
  done
fi

# 检查磁盘空间
check_disk_space "$WORK_DIR" 100 || exit 1

# 保存变更文件列表
printf '%s\n' "${FILES_CHANGED[@]}" > "$WORK_DIR/files_changed.txt"
log_info "共变更 ${#FILES_CHANGED[@]} 个文件"

# ============================================================
# [3/5] 运行测试（如果存在）
# ============================================================
log_info "[3/5] 运行测试..."

TEST_RESULT="skipped"
TEST_OUTPUT=""

if [[ "${TEST_MODE:-}" == "1" ]]; then
  log_info "[TEST_MODE] 模拟测试通过"
  TEST_RESULT="passed"
  TEST_OUTPUT="All tests passed (mock)"
else
  cd "$TARGET_PROJECT"

  if [[ "$PROJECT_TYPE" == "typescript" || "$PROJECT_TYPE" == "javascript" ]]; then
    if [[ -f "package.json" ]] && grep -q '"test"' package.json; then
      log_info "运行 npm test..."
      TEST_OUTPUT=$(npm test 2>&1) && TEST_RESULT="passed" || TEST_RESULT="failed"
    else
      log_info "未配置测试脚本，跳过"
    fi
  elif [[ "$PROJECT_TYPE" == "python" ]]; then
    if command -v pytest &>/dev/null; then
      log_info "运行 pytest..."
      TEST_OUTPUT=$(pytest --tb=short 2>&1) && TEST_RESULT="passed" || TEST_RESULT="failed"
    else
      log_info "pytest 未安装，跳过测试"
    fi
  fi

  cd - > /dev/null
fi

log_info "测试结果: $TEST_RESULT"

# ============================================================
# [4/5] 运行 Lint 检查
# ============================================================
log_info "[4/5] 运行 Lint 检查..."

LINT_RESULT="skipped"
LINT_OUTPUT=""

if [[ "${TEST_MODE:-}" == "1" ]]; then
  log_info "[TEST_MODE] 模拟 lint 通过"
  LINT_RESULT="passed"
  LINT_OUTPUT="No lint errors (mock)"
else
  cd "$TARGET_PROJECT"

  if [[ "$PROJECT_TYPE" == "typescript" || "$PROJECT_TYPE" == "javascript" ]]; then
    if [[ -f "package.json" ]] && grep -q '"lint"' package.json; then
      log_info "运行 npm run lint..."
      LINT_OUTPUT=$(npm run lint 2>&1) && LINT_RESULT="passed" || LINT_RESULT="warning"
    elif command -v eslint &>/dev/null; then
      log_info "运行 eslint..."
      LINT_OUTPUT=$(eslint --ext .ts,.js src/ 2>&1) && LINT_RESULT="passed" || LINT_RESULT="warning"
    fi
  elif [[ "$PROJECT_TYPE" == "python" ]]; then
    if command -v ruff &>/dev/null; then
      log_info "运行 ruff..."
      LINT_OUTPUT=$(ruff check . 2>&1) && LINT_RESULT="passed" || LINT_RESULT="warning"
    elif command -v flake8 &>/dev/null; then
      log_info "运行 flake8..."
      LINT_OUTPUT=$(flake8 . 2>&1) && LINT_RESULT="passed" || LINT_RESULT="warning"
    fi
  fi

  cd - > /dev/null
fi

log_info "Lint 结果: $LINT_RESULT"

# ============================================================
# 保存结果
# ============================================================
RESULT_SUCCESS=true
if [[ "$TEST_RESULT" == "failed" ]]; then
  RESULT_SUCCESS=false
fi

RESULT_ARTIFACTS=$(jq -n \
  --arg type "code" \
  --arg id "backend-${RUN_ID}" \
  --arg project "$TARGET_PROJECT" \
  --arg project_type "$PROJECT_TYPE" \
  --argjson file_count "${#FILES_CHANGED[@]}" \
  --arg test_result "$TEST_RESULT" \
  --arg lint_result "$LINT_RESULT" \
  '[{
    type: $type,
    id: $id,
    name: "Backend Code Generation",
    project: $project,
    project_type: $project_type,
    files_changed: $file_count,
    test_result: $test_result,
    lint_result: $lint_result
  }]')

save_result

# ============================================================
# [5/5] 生成截图报告
# ============================================================
log_info "[5/5] 生成执行结果截图..."

SAFE_PROJECT=$(html_escape "$TARGET_PROJECT")

# 生成文件变更列表 HTML
FILES_HTML=""
for f in "${FILES_CHANGED[@]}"; do
  SAFE_F=$(html_escape "$(basename "$f")")
  FILES_HTML+="<div class=\"info-row\"><span class=\"info-value\">📄 ${SAFE_F}</span></div>"
done

MAIN_CONTENT="
<div class=\"grid\">
  <div class=\"card\">
    <div class=\"card-title\">变更文件数</div>
    <div class=\"card-value\">${#FILES_CHANGED[@]} 个</div>
  </div>
  <div class=\"card\">
    <div class=\"card-title\">项目类型</div>
    <div class=\"card-value\">${PROJECT_TYPE}</div>
  </div>
</div>
<div class=\"card\">
  <div class=\"card-title\">目标项目</div>
  <div class=\"card-value\" style=\"font-size: 16px;\">${SAFE_PROJECT}</div>
</div>
<div class=\"card\">
  <div class=\"card-title\">测试结果</div>
  <div class=\"card-value $([ "$TEST_RESULT" == "passed" ] && echo "success")\">
    $([ "$TEST_RESULT" == "passed" ] && echo "✅" || echo "⚠️") ${TEST_RESULT}
  </div>
</div>
<div class=\"card\">
  <div class=\"card-title\">Lint 结果</div>
  <div class=\"card-value $([ "$LINT_RESULT" == "passed" ] && echo "success")\">
    $([ "$LINT_RESULT" == "passed" ] && echo "✅" || echo "⚠️") ${LINT_RESULT}
  </div>
</div>
<div class=\"card\">
  <div class=\"card-title\">变更文件</div>
  ${FILES_HTML}
</div>
"

REPORT_HTML=$(generate_result_report_html "Backend 代码生成完成" "✅" "$MAIN_CONTENT")
screenshot_html_report "$RUN_ID" "backend-execute-result" "$REPORT_HTML" || log_warn "结果截图失败"

# ============================================================
# 完成
# ============================================================
log_execute_end "Backend"

jq -n \
  --argjson success "$RESULT_SUCCESS" \
  --arg project "$TARGET_PROJECT" \
  --arg project_type "$PROJECT_TYPE" \
  --argjson file_count "${#FILES_CHANGED[@]}" \
  --arg test_result "$TEST_RESULT" \
  --arg lint_result "$LINT_RESULT" \
  '{
    success: $success,
    project: $project,
    project_type: $project_type,
    files_changed: $file_count,
    test_result: $test_result,
    lint_result: $lint_result
  }'
