import { FeatureManifest } from '../types';

const manifest: FeatureManifest = {
  id: 'system-hub',
  name: 'System',
  version: '1.0.0',
  source: 'core',
  instances: ['core'],

  navGroups: [
    { id: 'system', label: 'System', icon: 'Monitor', order: 5 },
  ],

  routes: [
    // Tab routes — all point to SystemTabbed which handles tab selection via URL
    {
      path: '/system',
      component: 'SystemTabbed',
      navItem: {
        label: 'System', icon: 'Monitor', group: 'system',
        children: [
          { path: '/system', label: 'Ops', icon: 'Activity', order: 1 },
          { path: '/system/cecelia', label: 'Cecelia', icon: 'Bot', order: 2 },
          { path: '/system/automation', label: 'Automation', icon: 'Workflow', order: 3 },
          { path: '/system/infra', label: 'Infrastructure', icon: 'Server', order: 4 },
          { path: '/system/claude', label: 'Claude', icon: 'Brain', order: 5 },
          { path: '/system/engine', label: 'Engine', icon: 'Cpu', order: 6 },
          { path: '/system/feature-map', label: 'Feature Map', icon: 'Map', order: 7 },
          { path: '/system/model-profile', label: '模型配置', icon: 'Settings', order: 8 },
          { path: '/live-monitor', label: 'Live Monitor', icon: 'Activity', order: 9 },
          { path: '/system/team', label: 'Team', icon: 'Users', order: 10 },
        ],
      },
    },
    { path: '/system/cecelia', component: 'SystemTabbed' },
    { path: '/system/automation', component: 'SystemTabbed' },
    { path: '/system/infra', component: 'SystemTabbed' },
    { path: '/system/claude', component: 'SystemTabbed' },
    { path: '/system/engine', component: 'SystemTabbed' },
    { path: '/system/feature-map', component: 'SystemTabbed' },
    { path: '/system/model-profile', component: 'SystemTabbed' },
    { path: '/system/team', component: 'SystemTabbed' },
    { path: '/system/staff', redirect: '/system/team' },
    { path: '/system/skills-registry', redirect: '/system/team' },
    // Drill-down routes (remain separate)
    { path: '/live-monitor', component: 'LiveMonitor' },
    { path: '/brain-status', component: 'BrainStatusDashboard' },
    { path: '/system/cecelia/runs', component: 'CeceliaRuns' },
    { path: '/system/cecelia/runs/:runId', component: 'RunDetail' },
    { path: '/system/cecelia/agents/:agentId', component: 'AgentDetail' },
    { path: '/system/n8n/workflows/:instance/:id', component: 'N8nWorkflowDetail' },
    { path: '/system/n8n/live-status/:instance/:executionId', component: 'N8nLiveStatusDetail' },
    { path: '/system/panorama', component: 'DevPanorama' },
    { path: '/system/panorama/repo/:repoName', component: 'RepoDetail' },
    { path: '/system/devgate', component: 'DevGateMetrics' },
    // Immune System routes
    { path: '/immune', component: 'ImmuneDashboard' },
    { path: '/immune/dashboard', component: 'ImmuneDashboard' },
    { path: '/immune/policies', component: 'ImmunePolicies' },
    { path: '/immune/policies/:id', component: 'ImmunePolicyDetail' },
    { path: '/immune/signatures', component: 'ImmuneSignatures' },
    { path: '/immune/signatures/:signature', component: 'ImmuneSignatureDetail' },
    // Redirects from old paths to new tab locations
    { path: '/system/ops', redirect: '/system' },
    { path: '/system/n8n/workflows', redirect: '/system/automation' },
    { path: '/system/n8n/live-status', redirect: '/system/automation' },
    { path: '/system/workers', redirect: '/system/automation' },
    { path: '/system/session-monitor', redirect: '/system/automation' },
    { path: '/system/infrastructure', redirect: '/system/infra' },
    { path: '/system/brain', redirect: '/system/engine' },
    { path: '/system/engine/capabilities', redirect: '/system/engine' },
    { path: '/system/operations', redirect: '/system' },
    // Removed pages → redirects
    { path: '/system/planner', redirect: '/dashboard/command' },
    { path: '/system/orchestrator', redirect: '/system/engine' },
    { path: '/system/canvas', redirect: '/work/project-panorama' },
    { path: '/system/project-panorama', redirect: '/work/project-panorama' },
    { path: '/system/vps-monitor', redirect: '/system/infra' },
    { path: '/system/performance', redirect: '/system/infra' },
    { path: '/system/claude-monitor', redirect: '/system/claude' },
    { path: '/system/claude-stats', redirect: '/system/claude' },
    { path: '/system/quality', redirect: '/system' },
    { path: '/system/live', redirect: '/system' },
    // Legacy short-form redirects
    { path: '/cecelia', redirect: '/system' },
    { path: '/cecelia/runs', redirect: '/system/cecelia/runs' },
    { path: '/engine', redirect: '/system/engine' },
    { path: '/engine/capabilities', redirect: '/system/engine' },
    { path: '/engine/dev-tasks', redirect: '/work' },
    { path: '/engine/session-monitor', redirect: '/system/automation' },
    { path: '/brain', redirect: '/system/engine' },
    { path: '/orchestrator', redirect: '/system/engine' },
    { path: '/n8n/workflows', redirect: '/system/automation' },
    { path: '/n8n/live-status', redirect: '/system/automation' },
    { path: '/workers', redirect: '/system/automation' },
    { path: '/planner', redirect: '/dashboard/command' },
    { path: '/panorama', redirect: '/system/panorama' },
    { path: '/canvas', redirect: '/work/project-panorama' },
    { path: '/project-panorama', redirect: '/work/project-panorama' },
    { path: '/vps-monitor', redirect: '/system/infra' },
    { path: '/performance', redirect: '/system/infra' },
    { path: '/claude-monitor', redirect: '/system/claude' },
    { path: '/claude-stats', redirect: '/system/claude' },
    { path: '/quality', redirect: '/system' },
    { path: '/devgate', redirect: '/system/engine' },
    // Legacy /ops redirects
    { path: '/ops', redirect: '/dashboard' },
    { path: '/ops/live', redirect: '/system' },
    { path: '/ops/cecelia', redirect: '/system' },
    { path: '/ops/cecelia/runs', redirect: '/system/cecelia/runs' },
    { path: '/ops/system/engine', redirect: '/system/engine' },
    { path: '/ops/system/capabilities', redirect: '/system/engine' },
    { path: '/ops/system/dev-tasks', redirect: '/work' },
    { path: '/ops/system/session-monitor', redirect: '/system/automation' },
    { path: '/ops/planner', redirect: '/dashboard/command' },
    { path: '/ops/planning', redirect: '/dashboard/command' },
    { path: '/ops/scheduler', redirect: '/today/queue' },
    { path: '/ops/roadmap', redirect: '/work/roadmap' },
    { path: '/ops/panorama', redirect: '/system/panorama' },
    { path: '/ops/panorama/canvas', redirect: '/work/project-panorama' },
    { path: '/ops/panorama/whiteboard', redirect: '/work/whiteboard' },
    { path: '/ops/panorama/project', redirect: '/work/project-panorama' },
    { path: '/ops/system', redirect: '/system/infra' },
    { path: '/ops/system/vps', redirect: '/system/infra' },
    { path: '/ops/claude', redirect: '/system/claude' },
    { path: '/ops/claude/stats', redirect: '/system/claude' },
    { path: '/ops/devgate', redirect: '/system/engine' },
    { path: '/planning', redirect: '/dashboard/command' },
    { path: '/company/ai-team', redirect: '/system/automation' },
    { path: '/company/ai-team/workers', redirect: '/system/automation' },
    { path: '/company/ai-team/workflows', redirect: '/system/automation' },
    { path: '/company/ai-team/live-status', redirect: '/system/automation' },
  ],

  components: {
    SystemTabbed: () => import('./pages/SystemTabbed'),
    // Drill-down pages
    LiveMonitor: () => import('../../../dashboard/src/pages/live-monitor/LiveMonitorPage'),
    BrainStatusDashboard: () => import('../execution/pages/BrainStatusDashboard'),
    CeceliaRuns: () => import('../execution/pages/CeceliaRuns'),
    RunDetail: () => import('../execution/pages/RunDetail'),
    AgentDetail: () => import('../execution/pages/AgentDetail'),
    N8nWorkflowDetail: () => import('../execution/pages/N8nWorkflowDetail'),
    N8nLiveStatusDetail: () => import('../execution/pages/N8nLiveStatusDetail'),
    DevGateMetrics: () => import('../system/pages/DevGateMetrics'),
    DevPanorama: () => import('../planning/pages/DevPanorama'),
    RepoDetail: () => import('../planning/pages/RepoDetail'),
    // Immune System pages
    ImmuneDashboard: () => import('../system/pages/immune/Dashboard'),
    ImmunePolicies: () => import('../system/pages/immune/Policies'),
    ImmunePolicyDetail: () => import('../system/pages/immune/PolicyDetail'),
    ImmuneSignatures: () => import('../system/pages/immune/Signatures'),
    ImmuneSignatureDetail: () => import('../system/pages/immune/SignatureDetail'),
  },
};

export default manifest;
