/**
 * Mock Feature Component
 * Generated by AI Factory Frontend Executor
 */

import React from 'react';

interface MockFeatureProps {
  title: string;
  description?: string;
  onAction?: () => void;
}

export const MockFeature: React.FC<MockFeatureProps> = ({
  title,
  description,
  onAction,
}) => {
  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <h3 className="text-lg font-semibold text-gray-900">{title}</h3>
      {description && (
        <p className="mt-2 text-sm text-gray-600">{description}</p>
      )}
      {onAction && (
        <button
          onClick={onAction}
          className="mt-4 px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
        >
          Action
        </button>
      )}
    </div>
  );
};

export default MockFeature;
