#!/bin/bash
#
# AI Factory v3.1 - 收尾阶段脚本
#
# 用法: cleanup.sh <task_id> <execution_result>
#
# 参数:
#   task_id          - Notion 任务 ID
#   execution_result - 执行结果 (success / failed)
#
# 流程:
#   1. 如果 success: 尝试合并到 main
#      - 合并成功 → 清理 worktree → AI Done
#      - 合并冲突 → 保留 worktree → AI Done (备注需人工处理)
#   2. 如果 failed: 保留 worktree → AI Failed
#   3. 更新 Notion 状态
#   4. 写执行报告到 Notion
#   5. 发飞书通知
#

set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.sh"
source "$SCRIPT_DIR/utils.sh"
source "$SCRIPT_DIR/worktree-manager.sh"

# ============================================================
# 参数解析
# ============================================================
TASK_ID="${1:-}"
EXECUTION_RESULT="${2:-}"

if [[ -z "$TASK_ID" || -z "$EXECUTION_RESULT" ]]; then
  echo "用法: cleanup.sh <task_id> <execution_result>"
  echo ""
  echo "参数:"
  echo "  task_id          Notion 任务 ID"
  echo "  execution_result success 或 failed"
  exit 1
fi

# 验证 execution_result
if [[ "$EXECUTION_RESULT" != "success" && "$EXECUTION_RESULT" != "failed" ]]; then
  log_error "execution_result 必须是 success 或 failed"
  exit 1
fi

BRANCH_NAME="${GIT_BRANCH_PREFIX}/${TASK_ID}"
WORKTREE_PATH="${WORKTREES_DIR}/${TASK_ID}"
LOG_FILE="${LOGS_DIR}/cleanup-${TASK_ID}.log"
NOTION_URL="https://notion.so/${TASK_ID//-/}"

# 确保日志目录存在
mkdir -p "$LOGS_DIR"

log_info "=========================================="
log_info "AI Factory v3.1 - 收尾阶段"
log_info "=========================================="
log_info "Task ID: $TASK_ID"
log_info "执行结果: $EXECUTION_RESULT"
log_info "分支: $BRANCH_NAME"
log_info "Worktree: $WORKTREE_PATH"
log_info "=========================================="

# ============================================================
# 获取任务信息
# ============================================================
log_info "[1/5] 获取任务信息..."

TASK_NAME="Unknown Task"

TASK_INFO=$(fetch_notion_task "$TASK_ID" 2>/dev/null) || true
if [[ -n "$TASK_INFO" ]]; then
  TASK_NAME=$(echo "$TASK_INFO" | jq -r '.task_name // "Unknown Task"')
fi

log_info "任务名称: $TASK_NAME"

# ============================================================
# 处理执行结果
# ============================================================
log_info "[2/5] 处理执行结果..."

FINAL_STATUS=""
MERGE_RESULT=""
HAS_CONFLICT=false
CONFLICT_FILES=""
REPORT_CONTENT=""

if [[ "$EXECUTION_RESULT" == "success" ]]; then
  log_info "执行成功，尝试合并到 $GIT_BASE_BRANCH..."

  # 先在 worktree 中提交更改（如果有）
  if [[ -d "$WORKTREE_PATH" ]]; then
    cd "$WORKTREE_PATH" || true
    if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
      log_info "提交 worktree 中的更改..."
      git add -A 2>/dev/null || true
      git commit -m "feat(${TASK_ID:0:8}): $TASK_NAME

Task: $NOTION_URL

Generated by AI Factory v3

Co-Authored-By: Claude <noreply@anthropic.com>" 2>/dev/null || true

      # 推送分支
      if timeout "$GIT_TIMEOUT" git push -u origin "$BRANCH_NAME" 2>/dev/null; then
        log_info "分支已推送: $BRANCH_NAME"
      else
        log_warn "推送分支失败"
      fi
    fi
  fi

  # 尝试合并
  MERGE_RESULT=$(merge_to_main "$BRANCH_NAME")

  case "$MERGE_RESULT" in
    success)
      log_info "合并成功"
      FINAL_STATUS="AI Done"

      # 清理 worktree
      if [[ "$CLEANUP_ON_SUCCESS" == "true" ]]; then
        log_info "清理 worktree..."
        cleanup_worktree "$TASK_ID" "true" || log_warn "清理 worktree 失败"
      fi

      REPORT_CONTENT="# 执行报告 [SUCCESS]

## 基本信息
- 任务: ${TASK_NAME}

- 状态: 成功
- 执行时间: $(date '+%Y-%m-%d %H:%M:%S')

## 合并结果
- 分支 ${BRANCH_NAME} 已成功合并到 ${GIT_BASE_BRANCH}
- Worktree 已清理

---
Generated by AI Factory v3"
      ;;

    conflict)
      log_warn "合并冲突"
      FINAL_STATUS="AI Done"
      HAS_CONFLICT=true

      # 获取冲突文件列表
      CONFLICT_FILES=$(get_conflict_files "$BRANCH_NAME" 2>/dev/null | head -20)

      log_warn "冲突文件列表:"
      echo "$CONFLICT_FILES" | while read -r file; do
        [[ -n "$file" ]] && log_warn "  - $file"
      done

      REPORT_CONTENT="# 执行报告 [CONFLICT]

## 基本信息
- 任务: ${TASK_NAME}

- 状态: 需人工处理合并冲突
- 执行时间: $(date '+%Y-%m-%d %H:%M:%S')

## 冲突信息
分支 ${BRANCH_NAME} 与 ${GIT_BASE_BRANCH} 存在合并冲突。

### 可能冲突的文件
${CONFLICT_FILES}

### 人工处理步骤
1. 进入 worktree 目录:
   cd ${WORKTREE_PATH}

2. 或者在主仓库处理:
   cd ${PROJECT_DIR}
   git checkout ${GIT_BASE_BRANCH}
   git pull origin ${GIT_BASE_BRANCH}
   git merge ${BRANCH_NAME}

3. 解决冲突后提交:
   git add .
   git commit
   git push origin ${GIT_BASE_BRANCH}

4. 清理 worktree:
   ${SCRIPT_DIR}/worktree-manager.sh cleanup ${TASK_ID}

---
Generated by AI Factory v3"
      ;;

    no_changes)
      log_info "没有更改需要合并"
      FINAL_STATUS="AI Done"

      # 清理 worktree
      if [[ "$CLEANUP_ON_SUCCESS" == "true" ]]; then
        cleanup_worktree "$TASK_ID" "true" || log_warn "清理 worktree 失败"
      fi

      REPORT_CONTENT="# 执行报告 [SUCCESS]

## 基本信息
- 任务: ${TASK_NAME}

- 状态: 成功 (无代码更改)
- 执行时间: $(date '+%Y-%m-%d %H:%M:%S')

## 备注
任务执行完成，但没有产生代码更改。

---
Generated by AI Factory v3"
      ;;

    error|*)
      log_error "合并失败"
      FINAL_STATUS="AI Failed"

      REPORT_CONTENT="# 执行报告 [FAILED]

## 基本信息
- 任务: ${TASK_NAME}

- 状态: 失败
- 执行时间: $(date '+%Y-%m-%d %H:%M:%S')

## 失败原因
合并操作失败，请检查分支状态。

### 调试信息
- 分支: ${BRANCH_NAME}
- Worktree: ${WORKTREE_PATH}

---
Generated by AI Factory v3"
      ;;
  esac

else
  # 执行失败
  log_error "执行失败，保留 worktree 用于调试"
  FINAL_STATUS="AI Failed"

  REPORT_CONTENT="# 执行报告 [FAILED]

## 基本信息
- 任务: ${TASK_NAME}

- 状态: 执行失败
- 执行时间: $(date '+%Y-%m-%d %H:%M:%S')

## 调试信息
- 分支: ${BRANCH_NAME}
- Worktree: ${WORKTREE_PATH} (已保留)

### 排查步骤
1. 进入 worktree 目录查看代码:
   cd ${WORKTREE_PATH}

2. 查看执行日志:
   cat ${LOG_FILE}

3. 修复后重新执行或手动完成

---
Generated by AI Factory v3"
fi

log_info "最终状态: $FINAL_STATUS"

# ============================================================
# 更新 Notion 状态
# ============================================================
log_info "[3/5] 更新 Notion 状态..."

if update_notion_status "$TASK_ID" "$FINAL_STATUS"; then
  log_info "Notion 状态已更新: $FINAL_STATUS"
else
  log_warn "更新 Notion 状态失败"
fi

# ============================================================
# 写报告到 Notion
# ============================================================
log_info "[4/5] 写执行报告到 Notion..."

if [[ -n "$REPORT_CONTENT" ]]; then
  if append_to_notion_page "$TASK_ID" "$REPORT_CONTENT"; then
    log_info "报告已写入 Notion"
  else
    log_warn "写入报告失败"
  fi
fi

# ============================================================
# 发送飞书通知
# ============================================================
log_info "[5/5] 发送飞书通知..."

FEISHU_TITLE=""
FEISHU_STATUS=""
FEISHU_CONTENT=""

if [[ "$FINAL_STATUS" == "AI Done" ]]; then
  if [[ "$HAS_CONFLICT" == "true" ]]; then
    FEISHU_TITLE="任务完成 - 需处理合并冲突"
    FEISHU_STATUS="warning"
    FEISHU_CONTENT="**任务**: ${TASK_NAME}

**状态**: 代码已完成，但有合并冲突

**冲突文件**:
\`\`\`
$(echo "$CONFLICT_FILES" | head -10)
\`\`\`

请手动处理合并冲突后，运行:
\`\`\`
${SCRIPT_DIR}/worktree-manager.sh cleanup ${TASK_ID}
\`\`\`"
  else
    FEISHU_TITLE="任务完成"
    FEISHU_STATUS="success"
    FEISHU_CONTENT="**任务**: ${TASK_NAME}

**状态**: 已完成并合并到 ${GIT_BASE_BRANCH}

请验收代码。"
  fi
else
  FEISHU_TITLE="任务执行失败"
  FEISHU_STATUS="failed"
  FEISHU_CONTENT="**任务**: ${TASK_NAME}

**状态**: 执行失败

**调试信息**:
- Worktree: \`${WORKTREE_PATH}\`
- 日志: \`${LOG_FILE}\`

请查看日志排查问题。"
fi

send_feishu_card "$FEISHU_TITLE" "$FEISHU_STATUS" "$FEISHU_CONTENT" "$NOTION_URL" || log_warn "飞书通知发送失败"

# ============================================================
# 输出结果
# ============================================================
log_info "=========================================="
log_info "收尾阶段完成"
log_info "=========================================="

# 输出 JSON 结果
jq -n \
  --arg task_id "$TASK_ID" \
  --arg execution_result "$EXECUTION_RESULT" \
  --arg final_status "$FINAL_STATUS" \
  --arg merge_result "$MERGE_RESULT" \
  --argjson has_conflict "$HAS_CONFLICT" \
  --arg worktree_path "$WORKTREE_PATH" \
  --arg branch_name "$BRANCH_NAME" \
  '{
    task_id: $task_id,
    execution_result: $execution_result,
    final_status: $final_status,
    merge_result: $merge_result,
    has_conflict: $has_conflict,
    worktree_path: $worktree_path,
    branch_name: $branch_name,
    timestamp: now | todate
  }'

# 返回状态码
if [[ "$FINAL_STATUS" == "AI Done" ]]; then
  exit 0
else
  exit 1
fi
