#!/bin/bash
#
# Feature Check 执行器
# 用于检查 Feature 相关的所有子任务是否完成
#
# 用法: execute.sh <run_id> <task_info_path>
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# v1.1: 使用固定位置的 shared 脚本
SHARED_DIR="/home/xx/bin/ai-factory-v2"

# 加载公共基础
source "$SHARED_DIR/execute-base.sh"

# 解析参数
parse_execute_args "$@"

# 打印开始日志
log_execute_start "Check"

# ============================================================
# 检查是否跳过执行（稳定性验证）
# ============================================================
if check_skip_execution "check"; then
  output_skip_result
  exit 0
fi

# ============================================================
# [1/4] 获取任务信息
# ============================================================
log_info "[1/4] 获取任务信息..."

TASK_NAME=$(json_get "$TASK_INFO_PATH" '.task_name' "Unknown Feature")
TASK_ID=$(json_get "$TASK_INFO_PATH" '.task_id' "")
BLOCKED_BY=$(json_get "$TASK_INFO_PATH" '.blocked_by' "[]")

log_info "Feature: $TASK_NAME"
log_info "Task ID: $TASK_ID"

# ============================================================
# [2/4] 检查所有依赖任务状态
# ============================================================
log_info "[2/4] 检查依赖任务状态..."

# 加载密钥
load_secrets

# 从 task_info.json 获取 blocked_by 列表
DEP_IDS=$(echo "$BLOCKED_BY" | jq -r '.[]? // empty' 2>/dev/null || echo "")

if [[ -z "$DEP_IDS" ]]; then
  log_info "没有依赖任务，Feature Check 通过"
  ALL_DONE=true
else
  ALL_DONE=true
  PENDING_TASKS=""
  COMPLETED_COUNT=0
  TOTAL_COUNT=0

  for DEP_ID in $DEP_IDS; do
    TOTAL_COUNT=$((TOTAL_COUNT + 1))

    # 查询 Notion 获取状态
    DEP_STATUS=$(curl -sf --connect-timeout 10 --max-time 30 \
      "https://api.notion.com/v1/pages/$DEP_ID" \
      -H "Authorization: Bearer $NOTION_API_KEY" \
      -H "Notion-Version: 2022-06-28" 2>/dev/null | \
      jq -r '.properties.Status.status.name // "unknown"' 2>/dev/null || echo "error")

    log_info "依赖任务 ${DEP_ID:0:8}... 状态: $DEP_STATUS"

    if [[ "$DEP_STATUS" == "AI Done" || "$DEP_STATUS" == "Completed" ]]; then
      COMPLETED_COUNT=$((COMPLETED_COUNT + 1))
    else
      ALL_DONE=false
      PENDING_TASKS="${PENDING_TASKS}${DEP_ID:0:8} ($DEP_STATUS), "
    fi
  done

  log_info "依赖任务完成进度: $COMPLETED_COUNT / $TOTAL_COUNT"
fi

if [[ "$ALL_DONE" == "false" ]]; then
  log_warn "部分依赖任务未完成: ${PENDING_TASKS%, }"

  # 保存结果
  jq -n \
    --argjson success false \
    --arg message "部分依赖任务未完成" \
    --arg pending "${PENDING_TASKS%, }" \
    --argjson completed "$COMPLETED_COUNT" \
    --argjson total "$TOTAL_COUNT" \
    '{
      success: $success,
      message: $message,
      pending_tasks: $pending,
      completed_count: $completed,
      total_count: $total
    }' > "$RESULT_PATH"

  # Feature Check 失败，返回非 0 退出码
  exit 1
fi

log_info "所有依赖任务已完成"

# ============================================================
# [3/4] 检查 Notion 页面是否有反馈
# ============================================================
log_info "[3/4] 检查反馈..."

PAGE_CONTENT_FILE="$RUN_DIR/page_content.md"
HAS_FEEDBACK=false
FEEDBACK_CONTENT=""

if [[ -f "$PAGE_CONTENT_FILE" ]]; then
  # 检查是否有 "## 反馈" 或 "## Feedback" 部分
  if grep -qE "^##\s*(反馈|Feedback)" "$PAGE_CONTENT_FILE"; then
    HAS_FEEDBACK=true
    # 提取反馈内容
    FEEDBACK_CONTENT=$(sed -n '/^##\s*\(反馈\|Feedback\)/,/^##/p' "$PAGE_CONTENT_FILE" | head -20)
    log_info "发现反馈内容"
  fi
fi

if [[ "$HAS_FEEDBACK" == "true" && -n "$FEEDBACK_CONTENT" ]]; then
  log_warn "Feature 有待处理的反馈，跳过自动验收"

  # 保存结果
  jq -n \
    --argjson success false \
    --arg message "Feature 有待处理的反馈" \
    --arg feedback "$FEEDBACK_CONTENT" \
    '{
      success: $success,
      message: $message,
      has_feedback: true,
      feedback: $feedback
    }' > "$RESULT_PATH"

  # 将状态改为 Waiting，等待反馈处理
  update_notion_status "$TASK_ID" "Waiting" || log_warn "更新状态失败"

  # 有反馈但不是失败，返回 0（让 cleanup.sh 处理状态）
  exit 0
fi

# ============================================================
# [4/4] 生成 Feature 汇总报告
# ============================================================
log_info "[4/4] 生成汇总报告..."

REPORT_FILE="$RUN_DIR/feature-report.md"
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

cat > "$REPORT_FILE" << EOF
# Feature Check Report

## 基本信息
- Feature: ${TASK_NAME}
- 检查时间: ${TIMESTAMP}
- Task ID: ${TASK_ID}

## 依赖任务 (${COMPLETED_COUNT:-0}/${TOTAL_COUNT:-0})
EOF

# 添加依赖任务列表
if [[ -n "$DEP_IDS" ]]; then
  echo "" >> "$REPORT_FILE"
  for dep_id in $DEP_IDS; do
    echo "- ${dep_id:0:8}... ✅" >> "$REPORT_FILE"
  done
fi

cat >> "$REPORT_FILE" << EOF

## 状态
- 所有依赖任务: ✅ 已完成
- 反馈检查: 没有待处理反馈
- 结论: **Feature Check 通过**

---
Generated by AI Factory v2 @ ${TIMESTAMP}
EOF

log_info "汇总报告已生成: $REPORT_FILE"

# 保存成功结果
jq -n \
  --argjson success true \
  --arg message "Feature Check 通过" \
  --arg feature_name "$TASK_NAME" \
  --arg report_file "$REPORT_FILE" \
  --argjson completed "${COMPLETED_COUNT:-0}" \
  --argjson total "${TOTAL_COUNT:-0}" \
  '{
    success: $success,
    message: $message,
    feature_name: $feature_name,
    report_file: $report_file,
    completed_count: $completed,
    total_count: $total
  }' > "$RESULT_PATH"

log_info "=========================================="
log_info "Feature Check 完成: 通过"
log_info "=========================================="

exit 0
