#!/bin/bash
#
# 收尾阶段脚本
# 负责：Git 提交推送、更新 Notion、发送通知、清理临时文件
#
# 用法: cleanup.sh <run_id> <task_id> <passed> [retry_count]
#
# 参数:
#   run_id      - 运行 ID
#   task_id     - Notion 任务 ID
#   passed      - true/false 质检是否通过
#   retry_count - 返工次数（可选，默认 0）
#
# 输出:
#   - 返回值: 0=成功, 非0=失败
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 加载工具函数
source "$SCRIPT_DIR/utils.sh"

# ============================================================
# 参数解析
# ============================================================
RUN_ID="${1:-}"
TASK_ID="${2:-}"
PASSED="${3:-false}"
RETRY_COUNT="${4:-0}"

if [[ -z "$RUN_ID" || -z "$TASK_ID" ]]; then
  log_error "用法: cleanup.sh <run_id> <task_id> <passed> [retry_count]"
  exit 1
fi

WORK_DIR="/home/xx/data/runs/$RUN_ID"
LOG_FILE="$WORK_DIR/logs/cleanup.log"

# 加载环境变量
if [[ -f "$WORK_DIR/env.sh" ]]; then
  source "$WORK_DIR/env.sh"
fi

log_info "=========================================="
log_info "收尾阶段开始"
log_info "Run ID: $RUN_ID"
log_info "Task ID: $TASK_ID"
log_info "质检结果: $PASSED"
log_info "返工次数: $RETRY_COUNT"
log_info "=========================================="

# ============================================================
# 步骤 1: Git 提交
# ============================================================
log_info "[1/6] Git 提交..."

cd "$PROJECT_DIR"

# 检查是否有更改需要提交
if [[ -n "$(git status --porcelain)" ]]; then
  # 读取任务名称
  TASK_NAME=""
  if [[ -f "$WORK_DIR/task_info.json" ]]; then
    TASK_NAME=$(jq -r '.task_name // "Unknown Task"' "$WORK_DIR/task_info.json")
  fi

  # 读取质检分数
  QUALITY_SCORE="N/A"
  if [[ -f "$WORK_DIR/quality_report.json" ]]; then
    QUALITY_SCORE=$(jq -r '.score // "N/A"' "$WORK_DIR/quality_report.json")
  fi

  # 构建 commit 消息
  COMMIT_TYPE="feat"
  COMMIT_SUFFIX=""

  if [[ "$PASSED" != "true" ]]; then
    COMMIT_TYPE="wip"
    COMMIT_SUFFIX=" (需人工处理)"
  elif [[ "$RETRY_COUNT" -gt 0 ]]; then
    COMMIT_SUFFIX=" [retry-$RETRY_COUNT]"
  fi

  COMMIT_MSG="${COMMIT_TYPE}(${TASK_ID:0:8}): ${TASK_NAME}${COMMIT_SUFFIX}

Task: https://notion.so/${TASK_ID}
Run ID: $RUN_ID
Quality Score: $QUALITY_SCORE/100
Retry Count: $RETRY_COUNT

Generated by AI Factory v2

Co-Authored-By: Claude <noreply@anthropic.com>"

  # 提交
  git add .
  git commit -m "$COMMIT_MSG" || {
    log_warn "Git commit 失败，可能没有实际更改"
  }

  log_info "Git 提交完成"
else
  log_info "没有更改需要提交"
fi

# ============================================================
# 步骤 2: Git 推送
# ============================================================
log_info "[2/6] Git 推送..."

BRANCH_NAME="${BRANCH_NAME:-feature/$TASK_ID}"

git push origin "$BRANCH_NAME" 2>/dev/null || {
  log_warn "Git push 失败，尝试设置 upstream..."
  git push -u origin "$BRANCH_NAME" || {
    log_error "Git push 失败"
    # 不退出，继续后续步骤
  }
}

log_info "Git 推送完成: $BRANCH_NAME"

# ============================================================
# 步骤 3: 更新 Notion 状态
# ============================================================
log_info "[3/6] 更新 Notion 状态..."

if [[ "$PASSED" == "true" ]]; then
  NEW_STATUS="Done"
  log_info "质检通过，状态更新为: Done"
else
  NEW_STATUS="Failed"
  log_info "质检失败，状态更新为: Failed (需人工处理)"
fi

update_notion_status "$TASK_ID" "$NEW_STATUS" || log_warn "更新 Notion 状态失败"

# ============================================================
# 步骤 4: 发送飞书通知
# ============================================================
log_info "[4/6] 发送飞书通知..."

# 读取结果信息
RESULT_SUMMARY=""
if [[ -f "$WORK_DIR/result.json" ]]; then
  ARTIFACT_COUNT=$(jq '.artifacts | length' "$WORK_DIR/result.json" 2>/dev/null || echo "0")
  RESULT_SUMMARY="产出物: ${ARTIFACT_COUNT} 个"
fi

QUALITY_SUMMARY=""
if [[ -f "$WORK_DIR/quality_report.json" ]]; then
  QUALITY_SCORE=$(jq -r '.score // "N/A"' "$WORK_DIR/quality_report.json")
  QUALITY_PASSED=$(jq -r '.passed' "$WORK_DIR/quality_report.json")
  QUALITY_SUMMARY="质检分数: ${QUALITY_SCORE}/100"
fi

# 构建通知内容
if [[ "$PASSED" == "true" ]]; then
  NOTIFY_STATUS="success"
  NOTIFY_TITLE="AI 工厂执行成功"
  NOTIFY_CONTENT="**任务**: ${TASK_NAME:-$TASK_ID}
**类型**: ${CODING_TYPE:-unknown}
**分支**: $BRANCH_NAME
$RESULT_SUMMARY
$QUALITY_SUMMARY
**Run ID**: $RUN_ID"
else
  NOTIFY_STATUS="failed"
  NOTIFY_TITLE="AI 工厂执行失败 - 需人工处理"
  NOTIFY_CONTENT="**任务**: ${TASK_NAME:-$TASK_ID}
**类型**: ${CODING_TYPE:-unknown}
**返工次数**: $RETRY_COUNT
$QUALITY_SUMMARY
**分支**: $BRANCH_NAME
**Run ID**: $RUN_ID

请检查代码并手动处理"
fi

send_feishu_card "$NOTIFY_TITLE" "$NOTIFY_STATUS" "$NOTIFY_CONTENT"

# ============================================================
# 步骤 5: 上传截图到 Notion
# ============================================================
log_info "[5/6] 上传截图..."

SCREENSHOTS_DIR="$WORK_DIR/screenshots"
if [[ -d "$SCREENSHOTS_DIR" ]] && [[ -n "$(ls -A "$SCREENSHOTS_DIR" 2>/dev/null)" ]]; then
  log_info "发现截图目录: $SCREENSHOTS_DIR"

  # 上传所有截图到 Notion
  upload_all_screenshots "$WORK_DIR" "$TASK_ID"

  # 发送第一张截图到飞书（作为完成证明）
  FIRST_SCREENSHOT=$(ls "$SCREENSHOTS_DIR"/*.png 2>/dev/null | head -1)
  if [[ -n "$FIRST_SCREENSHOT" ]]; then
    send_feishu_image "任务完成截图" "$FIRST_SCREENSHOT" "Task: ${TASK_NAME:-$TASK_ID}"
  fi
else
  log_info "没有截图需要上传"
fi

# ============================================================
# 步骤 6: 清理临时文件
# ============================================================
log_info "[6/6] 清理临时文件..."

# 保留运行目录（用于调试）
# 如果需要自动清理，可以启用以下代码：
# if [[ "$PASSED" == "true" ]]; then
#   log_info "质检通过，清理运行目录: $WORK_DIR"
#   rm -rf "$WORK_DIR"
# else
#   log_info "质检失败，保留运行目录供调试: $WORK_DIR"
# fi

log_info "运行目录保留: $WORK_DIR"

# 清理超过 7 天的旧运行目录（保留最近 50 个）
log_info "清理旧运行目录..."
RUNS_DIR="/home/xx/data/runs"
# 删除 7 天前的目录，但至少保留 50 个
OLD_DIRS=$(find "$RUNS_DIR" -maxdepth 1 -type d -name "20*" -mtime +7 2>/dev/null | sort | head -n -50)
if [[ -n "$OLD_DIRS" ]]; then
  echo "$OLD_DIRS" | xargs rm -rf 2>/dev/null || true
  log_info "已清理 $(echo "$OLD_DIRS" | wc -l) 个旧目录"
else
  log_info "没有需要清理的旧目录"
fi

# ============================================================
# 切换回 develop 分支
# ============================================================
# 注意：锁由 main.sh 统一管理，cleanup.sh 不再释放锁
log_info "切换回 develop 分支..."
cd "$PROJECT_DIR"
git checkout develop 2>/dev/null || git checkout main 2>/dev/null || true

# ============================================================
# 输出结果
# ============================================================
log_info "=========================================="
log_info "收尾阶段完成"
log_info "=========================================="

# 输出 JSON 结果
cat << EOF
{
  "success": true,
  "run_id": "$RUN_ID",
  "task_id": "$TASK_ID",
  "passed": $PASSED,
  "retry_count": $RETRY_COUNT,
  "branch_name": "$BRANCH_NAME",
  "notion_status": "$NEW_STATUS"
}
EOF
