/**
 * Mock feature generated by AI Factory
 * This is a test file for backend executor
 */

export interface MockFeature {
  id: string;
  name: string;
  createdAt: Date;
}

export function createMockFeature(name: string): MockFeature {
  return {
    id: `mock-${Date.now()}`,
    name,
    createdAt: new Date(),
  };
}

export function getMockFeatures(): MockFeature[] {
  return [
    createMockFeature('Feature 1'),
    createMockFeature('Feature 2'),
  ];
}
